// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcheck.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Xcheck.pbobjc.h"
#import "Xchain.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - XcheckRoot

@implementation XcheckRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - XcheckRoot_FileDescriptor

static GPBFileDescriptor *XcheckRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"pb"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ComplianceCheckResponse

@implementation ComplianceCheckResponse

@dynamic hasHeader, header;
@dynamic hasSignature, signature;

typedef struct ComplianceCheckResponse__storage_ {
  uint32_t _has_storage_[1];
  Header *header;
  SignatureInfo *signature;
} ComplianceCheckResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "header",
        .dataTypeSpecific.className = GPBStringifySymbol(Header),
        .number = ComplianceCheckResponse_FieldNumber_Header,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ComplianceCheckResponse__storage_, header),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "signature",
        .dataTypeSpecific.className = GPBStringifySymbol(SignatureInfo),
        .number = ComplianceCheckResponse_FieldNumber_Signature,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ComplianceCheckResponse__storage_, signature),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ComplianceCheckResponse class]
                                     rootClass:[XcheckRoot class]
                                          file:XcheckRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ComplianceCheckResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransferCheckResponse

@implementation TransferCheckResponse

@dynamic hasHeader, header;
@dynamic hasSignature, signature;

typedef struct TransferCheckResponse__storage_ {
  uint32_t _has_storage_[1];
  Header *header;
  SignatureInfo *signature;
} TransferCheckResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "header",
        .dataTypeSpecific.className = GPBStringifySymbol(Header),
        .number = TransferCheckResponse_FieldNumber_Header,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TransferCheckResponse__storage_, header),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "signature",
        .dataTypeSpecific.className = GPBStringifySymbol(SignatureInfo),
        .number = TransferCheckResponse_FieldNumber_Signature,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(TransferCheckResponse__storage_, signature),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransferCheckResponse class]
                                     rootClass:[XcheckRoot class]
                                          file:XcheckRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransferCheckResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
