// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xendorser.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Header;
@class SignatureInfo;
@class Transaction;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - XendorserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface XendorserRoot : GPBRootObject
@end

#pragma mark - EndorserRequest

typedef GPB_ENUM(EndorserRequest_FieldNumber) {
  EndorserRequest_FieldNumber_Header = 1,
  EndorserRequest_FieldNumber_RequestName = 2,
  EndorserRequest_FieldNumber_BcName = 3,
  EndorserRequest_FieldNumber_Fee = 4,
  EndorserRequest_FieldNumber_RequestData = 5,
};

/**
 * 请求参数
 **/
@interface EndorserRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Header *header;
/** Test to see if @c header has been set. */
@property(nonatomic, readwrite) BOOL hasHeader;

/** 请求名(类型) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestName;

/** 请求链名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bcName;

/** 带签名的交易费Tx */
@property(nonatomic, readwrite, strong, null_resettable) Transaction *fee;
/** Test to see if @c fee has been set. */
@property(nonatomic, readwrite) BOOL hasFee;

/** Json打包的数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *requestData;

@end

#pragma mark - EndorserResponse

typedef GPB_ENUM(EndorserResponse_FieldNumber) {
  EndorserResponse_FieldNumber_Header = 1,
  EndorserResponse_FieldNumber_ResponseName = 2,
  EndorserResponse_FieldNumber_EndorserAddress = 3,
  EndorserResponse_FieldNumber_EndorserSign = 4,
  EndorserResponse_FieldNumber_ResponseData = 5,
};

@interface EndorserResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Header *header;
/** Test to see if @c header has been set. */
@property(nonatomic, readwrite) BOOL hasHeader;

@property(nonatomic, readwrite, copy, null_resettable) NSString *responseName;

/** 背书服务地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endorserAddress;

/** 背书服务签名 */
@property(nonatomic, readwrite, strong, null_resettable) SignatureInfo *endorserSign;
/** Test to see if @c endorserSign has been set. */
@property(nonatomic, readwrite) BOOL hasEndorserSign;

@property(nonatomic, readwrite, copy, null_resettable) NSData *responseData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
